<?php

namespace srag\Plugins\M365File\ObjectSettings;

use srag\Plugins\M365File\ObjectSettings\Form\FormBuilder;
use srag\Plugins\M365File\Utils\M365FileTrait;
use ilM365FilePlugin;
use ilObjM365File;
use ilObjM365FileGUI;
use srag\DIC\M365File\DICTrait;

/**
 * Class Factory
 *
 * Generated by SrPluginGenerator v2.8.1
 *
 * @package srag\Plugins\M365File\ObjectSettings
 *
 * @author studer + raimann ag <support@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
final class Factory
{

    use DICTrait;
    use M365FileTrait;

    const PLUGIN_CLASS_NAME = ilM365FilePlugin::class;
    /**
     * @var self|null
     */
    protected static $instance = null;


    /**
     * Factory constructor
     */
    private function __construct()
    {

    }


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * @param ilObjM365FileGUI $parent
     * @param ilObjM365File    $object
     *
     * @return FormBuilder
     */
    public function newFormBuilderInstance(ilObjM365FileGUI $parent, ilObjM365File $object) : FormBuilder
    {
        $form = new FormBuilder($parent, $object);

        return $form;
    }


    /**
     * @return ObjectSettings
     */
    public function newInstance() : ObjectSettings
    {
        $object_settings = new ObjectSettings();

        return $object_settings;
    }
}
