<?php

use srag\Plugins\M365File\Utils\M365FileTrait;
use srag\DIC\M365File\DICTrait;
use Microsoft\Graph\Exception\GraphException;
use League\OAuth2\Client\Provider\Exception\IdentityProviderException;

/**
 * Class ilObjM365FileGUI
 *
 * Generated by SrPluginGenerator v2.8.1
 *
 * @author studer + raimann ag <support@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 *
 * @ilCtrl_isCalledBy ilObjM365FileGUI: ilRepositoryGUI
 * @ilCtrl_isCalledBy ilObjM365FileGUI: ilObjPluginDispatchGUI
 * @ilCtrl_isCalledBy ilObjM365FileGUI: ilAdministrationGUI
 * @ilCtrl_Calls      ilObjM365FileGUI: ilPermissionGUI
 * @ilCtrl_Calls      ilObjM365FileGUI: ilInfoScreenGUI
 * @ilCtrl_Calls      ilObjM365FileGUI: ilObjectCopyGUI
 * @ilCtrl_Calls      ilObjM365FileGUI: ilCommonActionDispatcherGUI
 */
class ilObjM365FileGUI extends ilObjectPluginGUI
{

    use DICTrait;
    use M365FileTrait;

    const CMD_MANAGE_CONTENTS = "manageContents";
    const CMD_PERMISSIONS = "perm";
    const CMD_SETTINGS = "settings";
    const CMD_SETTINGS_STORE = "settingsStore";
    const CMD_SHOW_CONTENTS = "showContents";
    const LANG_MODULE_OBJECT = "object";
    const LANG_MODULE_SETTINGS = "settings";
    const PLUGIN_CLASS_NAME = ilM365FilePlugin::class;
    const TAB_CONTENTS = "contents";
    const TAB_PERMISSIONS = "perm_settings";
    const TAB_SETTINGS = "settings";
    const TAB_SHOW_CONTENTS = "show_contents";
    const POST_FILE = 'upload_file';

    private static $m365_formats = [
        'doc',
        'docx',
        'dot',
        'dotx',
        'xls',
        'xlsx',
        'xlt',
        'xltx',
        'ppt',
        'pptx',
    ];

    /**
     * @var ilObjM365File
     */
    public $object;


    /**
     * @return string
     */
    public static function getStartCmd() : string
    {
        if (ilObjM365FileAccess::hasWriteAccess()) {
            return self::CMD_MANAGE_CONTENTS;
        } else {
            return self::CMD_SHOW_CONTENTS;
        }
    }

    /**
     * @inheritDoc
     */
    public function getAfterCreationCmd() : string
    {
        return self::getStartCmd();
    }


    /**
     * @inheritDoc
     */
    public function getStandardCmd() : string
    {
        return self::getStartCmd();
    }


    /**
     * @inheritDoc
     */
    public final function getType() : string
    {
        return ilM365FilePlugin::PLUGIN_ID;
    }


    /**
     * @inheritDoc
     */
    public function initCreateForm(/*string*/ $a_new_type) : ilPropertyFormGUI
    {
        $form = parent::initCreateForm($a_new_type);

        $file_input = new ilFileInputGUI($this->plugin->txt('creation_file_input'), self::POST_FILE);
        $file_input->setSuffixes(self::$m365_formats);
        $file_input->setRequired(true);
        $form->addItem($file_input);

        return $form;
    }


    public function save()
    {
        $form = $this->initCreateForm($this->getType());
        $form->setValuesByPost();
        $form->checkInput();
        /** @var array $file */
        $file = $form->getInput(self::POST_FILE);
        if ($file['error'] > 0) {
            throw new ilException("file upload failed with error code " . $file['error']);
        }
        parent::save();
        // we create the sharepoint folder & file in afterSave, because we need a ref_id
    }

    /**
     * @inheritDoc
     * @param ilObject $a_new_object
     * @throws IdentityProviderException
     * @throws GraphException
     */
    public function afterSave(/*ilObjM365File*/ ilObject $a_new_object)/* : void*/
    {
        $form = $this->initCreateForm($this->getType());
        $form->setValuesByPost();
        $form->checkInput();
        /** @var array $file */
        $file = $form->getInput(self::POST_FILE);
        self::restClient()->createFolder($a_new_object->getRefId());
        $file = $this->restClient()->uploadFile(
            $file['tmp_name'],
            $file['name'],
            $a_new_object->getRefId()
        );
        $settings = self::m365File()->objectSettings()->getObjectSettingsById($a_new_object->getId());
        $settings->setSharingLink(self::restClient()->createSharingLink($file->getBody()['id']));
        self::m365File()->objectSettings()->storeObjectSettings(
            $settings
        );
        parent::afterSave($a_new_object);
    }

    /**
     * @param string $cmd
     */
    public function performCommand(string $cmd)/* : void*/
    {
        self::dic()->help()->setScreenIdComponent(ilM365FilePlugin::PLUGIN_ID);
        self::dic()->ui()->mainTemplate()->setPermanentLink(ilM365FilePlugin::PLUGIN_ID, $this->object->getRefId());

        $next_class = self::dic()->ctrl()->getNextClass($this);

        switch (strtolower($next_class)) {
            default:
                switch ($cmd) {
                    case self::CMD_SHOW_CONTENTS:
                        // Read commands
                        if (!ilObjM365FileAccess::hasReadAccess()) {
                            ilObjM365FileAccess::redirectNonAccess(ilRepositoryGUI::class);
                        }

                        $this->{$cmd}();
                        break;

                    case self::CMD_MANAGE_CONTENTS:
                    case self::CMD_SETTINGS:
                    case self::CMD_SETTINGS_STORE:
                        // Write commands
                        if (!ilObjM365FileAccess::hasWriteAccess()) {
                            ilObjM365FileAccess::redirectNonAccess($this);
                        }

                        $this->{$cmd}();
                        break;

                    default:
                        // Unknown command
                        ilObjM365FileAccess::redirectNonAccess(ilRepositoryGUI::class);
                        break;
                }
                break;
        }
    }


    /**
     * @inheritDoc
     */
    protected function afterConstructor()/* : void*/
    {

    }


    /**
     *
     */
    protected function manageContents()/* : void*/
    {
        self::dic()->tabs()->activateTab(self::TAB_CONTENTS);

        // TODO: Implement manageContents
        $this->show("");
    }


    /**
     *
     */
    protected function setTabs()/* : void*/
    {
        self::dic()->tabs()->addTab(self::TAB_SHOW_CONTENTS, self::plugin()->translate("show_contents", self::LANG_MODULE_OBJECT), $this->object->getObjectSettings()->getSharingLink());

        if (ilObjM365FileAccess::hasWriteAccess()) {
            self::dic()->tabs()->addTab(self::TAB_CONTENTS, self::plugin()->translate("manage_contents", self::LANG_MODULE_OBJECT), self::dic()
                ->ctrl()->getLinkTarget($this, self::CMD_MANAGE_CONTENTS));

            self::dic()->tabs()->addTab(self::TAB_SETTINGS, self::plugin()->translate("settings", self::LANG_MODULE_SETTINGS), self::dic()->ctrl()
                ->getLinkTarget($this, self::CMD_SETTINGS));
        }

        if (ilObjM365FileAccess::hasEditPermissionAccess()) {
            self::dic()->tabs()->addTab(self::TAB_PERMISSIONS, self::plugin()->translate(self::TAB_PERMISSIONS, "", [], false), self::dic()->ctrl()
                ->getLinkTargetByClass([
                    self::class,
                    ilPermissionGUI::class
                ], self::CMD_PERMISSIONS));
        }

        self::dic()->tabs()->manual_activation = true; // Show all tabs as links when no activation
    }


    /**
     *
     */
    protected function settings()/* : void*/
    {
        self::dic()->tabs()->activateTab(self::TAB_SETTINGS);

        $form = self::m365File()->objectSettings()->factory()->newFormBuilderInstance($this, $this->object);

        self::output()->output($form);
    }


    /**
     *
     */
    protected function settingsStore()/* : void*/
    {
        self::dic()->tabs()->activateTab(self::TAB_SETTINGS);

        $form = self::m365File()->objectSettings()->factory()->newFormBuilderInstance($this, $this->object);

        if (!$form->storeForm()) {
            self::output()->output($form);

            return;
        }

        ilUtil::sendSuccess(self::plugin()->translate("saved", self::LANG_MODULE_SETTINGS), true);

        self::dic()->ctrl()->redirect($this, self::CMD_SETTINGS);
    }


    /**
     * @param string $html
     */
    protected function show(string $html)/* : void*/
    {
        if (!self::dic()->ctrl()->isAsynch()) {
            self::dic()->ui()->mainTemplate()->setTitle($this->object->getTitle());

            self::dic()->ui()->mainTemplate()->setDescription($this->object->getDescription());

            if (!$this->object->isOnline()) {
                self::dic()->ui()->mainTemplate()->setAlertProperties([
                    [
                        "alert"    => true,
                        "property" => self::plugin()->translate("status", self::LANG_MODULE_OBJECT),
                        "value"    => self::plugin()->translate("offline", self::LANG_MODULE_OBJECT)
                    ]
                ]);
            }
        }

        self::output()->output($html);
    }


    /**
     *
     */
    protected function showContents()/* : void*/
    {
        self::dic()->tabs()->activateTab(self::TAB_SHOW_CONTENTS);

        // TODO: Implement showContents
        $this->show("");
    }

    protected function supportsCloning()
    {
        return false;
    }

}
