<?php

use srag\Plugins\M365File\ObjectSettings\ObjectSettings;
use srag\Plugins\M365File\Utils\M365FileTrait;
use srag\DIC\M365File\DICTrait;

/**
 * Class ilObjM365File
 *
 * Generated by SrPluginGenerator v2.8.1
 *
 * @author studer + raimann ag <support@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ilObjM365File extends ilObjectPlugin
{

    use DICTrait;
    use M365FileTrait;

    const PLUGIN_CLASS_NAME = ilM365FilePlugin::class;
    /**
     * @var ObjectSettings|null
     */
    protected $object_settings = null;


    /**
     * ilObjM365File constructor
     *
     * @param int $a_ref_id
     */
    public function __construct(/*int*/ $a_ref_id = 0)
    {
        parent::__construct($a_ref_id);
    }


    /**
     * @inheritDoc
     */
    public function doCreate()/* : void*/
    {
        $this->object_settings = self::m365File()->objectSettings()->factory()->newInstance();

        $this->object_settings->setObjId($this->id);

        self::m365File()->objectSettings()->storeObjectSettings($this->object_settings);
    }


    /**
     * @inheritDoc
     */
    public function doDelete()/* : void*/
    {
        if ($this->object_settings !== null) {
            self::m365File()->objectSettings()->deleteObjectSettings($this->object_settings);
        }
    }


    /**
     * @inheritDoc
     */
    public function doRead()/* : void*/
    {
        $this->object_settings = self::m365File()->objectSettings()->getObjectSettingsById(intval($this->id));
    }


    /**
     * @inheritDoc
     */
    public function doUpdate()/* : void*/
    {
        self::m365File()->objectSettings()->storeObjectSettings($this->object_settings);
    }


    /**
     * @inheritDoc
     */
    public final function initType()/* : void*/
    {
        $this->setType(ilM365FilePlugin::PLUGIN_ID);
    }


    /**
     * @return bool
     */
    public function isOnline() : bool
    {
        return $this->object_settings->isOnline();
    }


    /**
     * @param bool $is_online
     */
    public function setOnline(bool $is_online = true)/* : void*/
    {
        $this->object_settings->setOnline($is_online);
    }


    /**
     * @inheritDoc
     *
     * @param ilObjM365File $new_obj
     */
    protected function doCloneObject(/*ilObjM365File*/ $new_obj, /*int*/ $a_target_id, /*?int*/ $a_copy_id = null)/* : void*/
    {
        $new_obj->object_settings = self::m365File()->objectSettings()->cloneObjectSettings($this->object_settings);

        $new_obj->object_settings->setObjId($new_obj->id);

        self::m365File()->objectSettings()->storeObjectSettings($new_obj->object_settings);
    }

    /**
     * @return ObjectSettings|null
     */
    public function getObjectSettings() : ObjectSettings
    {
        return $this->object_settings;
    }
}
