<?php

require_once __DIR__ . "/../vendor/autoload.php";

use srag\Plugins\M365File\Utils\M365FileTrait;
use ILIAS\DI\Container;
use srag\CustomInputGUIs\M365File\Loader\CustomInputGUIsLoaderDetector;
use srag\DevTools\M365File\DevToolsCtrl;
use srag\RemovePluginDataConfirm\M365File\RepositoryObjectPluginUninstallTrait;

/**
 * Class ilM365FilePlugin
 *
 * Generated by SrPluginGenerator v2.8.1
 *
 * @author studer + raimann ag <support@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ilM365FilePlugin extends ilRepositoryObjectPlugin
{

    use RepositoryObjectPluginUninstallTrait;
    use M365FileTrait;

    const PLUGIN_CLASS_NAME = self::class;
    const PLUGIN_ID = "xmsf";
    const PLUGIN_NAME = "M365File";
    /**
     * @var self|null
     */
    protected static $instance = null;


    /**
     * ilM365FilePlugin constructor
     */
    public function __construct()
    {
        parent::__construct();
    }


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * @inheritDoc
     */
    public function exchangeUIRendererAfterInitialization(Container $dic) : Closure
    {
        return CustomInputGUIsLoaderDetector::exchangeUIRendererAfterInitialization();
    }


    /**
     * @inheritDoc
     */
    public function getPluginName() : string
    {
        return self::PLUGIN_NAME;
    }


    /**
     * @inheritDoc
     */
    public function updateLanguages(/*?array*/ $a_lang_keys = null)/* : void*/
    {
        parent::updateLanguages($a_lang_keys);

        $this->installRemovePluginDataConfirmLanguages();
    }


    /**
     * @inheritDoc
     */
    protected function deleteData()/* : void*/
    {
        self::m365File()->dropTables();
    }


    /**
     * @inheritDoc
     */
    protected function shouldUseOneUpdateStepOnly() : bool
    {
        return false;
    }
}
