<?php

namespace srag\Plugins\M365File;

use srag\Plugins\M365File\Config\Repository as ConfigRepository;
use srag\Plugins\M365File\ObjectSettings\Repository as ObjectSettingsRepository;
use srag\Plugins\M365File\Utils\M365FileTrait;
use ilM365FilePlugin;
use srag\DIC\M365File\DICTrait;

/**
 * Class Repository
 *
 * Generated by SrPluginGenerator v2.8.1
 *
 * @package srag\Plugins\M365File
 *
 * @author studer + raimann ag <support@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
final class Repository
{

    use DICTrait;
    use M365FileTrait;

    const PLUGIN_CLASS_NAME = ilM365FilePlugin::class;
    /**
     * @var self|null
     */
    protected static $instance = null;


    /**
     * Repository constructor
     */
    private function __construct()
    {

    }


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * @return ConfigRepository
     */
    public function config() : ConfigRepository
    {
        return ConfigRepository::getInstance();
    }


    /**
     *
     */
    public function dropTables()/* : void*/
    {
        $this->config()->dropTables();
        $this->objectSettings()->dropTables();
    }


    /**
     *
     */
    public function installTables()/* : void*/
    {
        $this->config()->installTables();
        $this->objectSettings()->installTables();
    }


    /**
     * @return ObjectSettingsRepository
     */
    public function objectSettings() : ObjectSettingsRepository
    {
        return ObjectSettingsRepository::getInstance();
    }
}
